### ISSUE TITLE
Can't install bioinfokit

### ISSUE THREAD

**Issue by ZJJane** [reneshbedre/bioinfokit#38]
executed command:
pip install --index-url https://pypi.tuna.tsinghua.edu.cn/simple/ bioinfokit

output:
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/

WARNING: Ignoring invalid distribution -illow (f:\python3.8\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (f:\python3.8\lib\site-packages)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory'))': /simple/bioinfokit/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory'))': /simple/bioinfokit/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory'))': /simple/bioinfokit/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory'))': /simple/bioinfokit/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory'))': /simple/bioinfokit/
ERROR: Could not find a version that satisfies the requirement bioinfokit (from versions: none)
ERROR: No matching distribution found for bioinfokit
WARNING: Ignoring invalid distribution -illow (f:\python3.8\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (f:\python3.8\lib\site-packages)

executed command:
easy_install bioinfokit

output:
WARNING: The easy_install command is deprecated and will be removed in a future version.
Searching for bioinfokit
Reading https://pypi.org/simple/bioinfokit/
Downloading https://files.pythonhosted.org/packages/e1/32/e1581d40b9e1f88c496b854002ab00f45c47880909f8a529ced2e7ea7314/bioinfokit-2.0.6.tar.gz#sha256=5552eecd98f3ad90bc39939bfbb50a933c7b0a4159360bc386555795c035e8e3
Best match: bioinfokit 2.0.6
Processing bioinfokit-2.0.6.tar.gz
Writing C:\Users\MSI\AppData\Local\Temp\easy_install-sjpi64h8\bioinfokit-2.0.6\setup.cfg
Running bioinfokit-2.0.6\setup.py -q bdist_egg --dist-dir C:\Users\MSI\AppData\Local\Temp\easy_install-sjpi64h8\bioinfokit-2.0.6\egg-dist-tmp-gju5ypax
Traceback (most recent call last):
  File "f:\python3.8\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "f:\python3.8\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "f:\python3.8\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "f:\python3.8\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "C:\Users\MSI\AppData\Local\Temp\easy_install-sjpi64h8\bioinfokit-2.0.6\setup.py", line 5, in <module>
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 63494: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\python3.8\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "f:\python3.8\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\python3.8\Scripts\easy_install.exe\__main__.py", line 7, in <module>
  File "f:\python3.8\lib\site-packages\setuptools\command\easy_install.py", line 2307, in main
    setup(
  File "f:\python3.8\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "f:\python3.8\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "f:\python3.8\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "f:\python3.8\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "f:\python3.8\lib\site-packages\setuptools\command\easy_install.py", line 425, in run
    self.easy_install(spec, not self.no_deps)
  File "f:\python3.8\lib\site-packages\setuptools\command\easy_install.py", line 686, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "f:\python3.8\lib\site-packages\setuptools\command\easy_install.py", line 712, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "f:\python3.8\lib\site-packages\setuptools\command\easy_install.py", line 897, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "f:\python3.8\lib\site-packages\setuptools\command\easy_install.py", line 1167, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "f:\python3.8\lib\site-packages\setuptools\command\easy_install.py", line 1151, in run_setup
    run_setup(setup_script, args)
  File "f:\python3.8\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
    raise
  File "f:\python3.8\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "f:\python3.8\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "f:\python3.8\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "f:\python3.8\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "f:\python3.8\lib\site-packages\setuptools\sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "f:\python3.8\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "f:\python3.8\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "f:\python3.8\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "f:\python3.8\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "f:\python3.8\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "C:\Users\MSI\AppData\Local\Temp\easy_install-sjpi64h8\bioinfokit-2.0.6\setup.py", line 5, in <module>
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 63494: illegal multibyte sequence

OS: Windows10
Python version: 3.8

**Comment by ZJJane** [comment]
I found the way to fix it.
https://github.com/sshwsfc/xadmin/issues/330
