### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by Yu1833** [reneshbedre/bioinfokit#62]
Hello Renesh,
Thanks for your contribution for bioinformatics analysis. 
Recently I started to use the bioinfokit packages, I try to install it. But when I installed it, some errors below happened. I've installed all the required packages. I tried many methods: install manually, and change a new environment, but all of them didn't work. Could you give me some advise to solve this problem?  I really need this packages to help me analyze my data. I'll appreciate if you help me to solve this problem. 
Thanks in advance!

Collecting bioinfokit
  Downloading bioinfokit-2.1.0.tar.gz (86 kB)
     ---------------------------------------- 0.0/87.0 kB ? eta -:--:--
     ---------------------------------------- 87.0/87.0 kB 5.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\**\AppData\Local\Temp\pip-install-bcd2lf9m\bioinfokit_79581f97ef134abda1f4bec4ac897425\setup.py", line 2, in <module>
      import bioinfokit
  ModuleNotFoundError: No module named 'bioinfokit'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by reneshbedre** [comment]
Did you try it with conda? I did not see any issue from my side and no one also reported before. I feel this is environment-related issue. Please use conda and see if the error persists,
